//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Passengers = new HashSet<Passenger>();
        }
    
        public int TicketId { get; set; }
        public int UserId { get; set; }
        public int FlightId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public int TotalPassengers { get; set; }
        public decimal TotalCost { get; set; }
        public string Status { get; set; }
    
        public virtual Flight Flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passengers { get; set; }
        public virtual User User { get; set; }
    }
}
